import { baloo } from '@/app/ui/fonts';
import "./globals.css";
import Providers from './Providers';
import Footer from '@/components/Footer';
import Siderbar from '@/components/Siderbar';



export const metadata = {
  title: "Die Wortschatzkartei",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="de">

      <body className={`${baloo.className} flex flex-row`}>
        <Providers>
          <Siderbar/>
            {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
