import { baloo } from '@/app/ui/fonts';
import "./globals.css";
import Providers from './Providers';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';



export const metadata = {
  title: "Die Wortschatzkartei",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="de">

      <body className={`${baloo.className}`}>
        <Providers>
          <Navbar />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
